use master

create database TescaOLTP    --- OLTP 

create database TescaStaging

create database TescaEDW

create database TescaControl

use TescaOLTP
select * from Product
select * from PurchaseTransaction

select * from SalesTransaction

select * from Employee Where EmployeeID=366

date                                  Hour
2020-04-07                              0-23   --   

Total sales generated by Salesperson to determine Staff promotion and Bonus

select EmployeeID, Sum(LineAmount) as TotalSales, Count(*) from SalesTransaction
Group by  EmployeeID
order by TotalSales desc

--- Schema Creation
use TescaStaging
create schema retail
create schema hr

use TescaEDW
create schema edw


---drop schema hr
-------------Store ----
--- Loading staging
use TescaOLTP
select s.StoreID,s.StoreName,s.StreetAddress,c.CityName, st.State, getdate() as LoadDate   from Store s
inner join City c on s.CityID=c.CityID
inner join State st on st.StateID=c.StateID


select count(*) as stgSourceCount  from Store s
inner join City c on s.CityID=c.CityID
inner join State st on st.StateID=c.StateID



use TescaStaging

select * from retail.Store

IF OBJECT_ID('retail.store') is not null
	Truncate Table retail.store;

create table retail.Store
(
  StoreID int, 
  StoreName nvarchar(50),
  StreetAddress nvarchar(50),
  CityName nvarchar(50),
  State nvarchar(50),
  LoadDate datetime default getdate(),
  constraint retail_store_pk  primary key(StoreID) 
 )
 

 -----Loading Store EDW
 use TescaStaging
 select  storeID,StoreName,StreetAddress,CityName,State  from retail.Store

 Use TescaEDW
 
 select count(*) as PreCount from edw.dimstore

 select * from edw.dimstore

 select count(*) as PostCount from edw.dimstore


 create table edw.dimstore
 (
  StoreSK int identity(1,1),
  StoreID int, 
  StoreName nvarchar(50),
  StreetAddress nvarchar(50),
  CityName nvarchar(50),
  State nvarchar(50),
  EffectiveStartDate datetime default getdate(),
  constraint edw_dimstore_sk primary key(StoreSk)
  )

----- product 

---- Loading staging 
use TescaOLTP

select p.ProductID,p.ProductNumber,p.Product, d.Department ,p.UnitPrice, getdate() as LoadDate  from Product p 
inner join Department d on p.DepartmentID=d.DepartmentID

select count(*) as stgSourceCount from Product p 
inner join Department d on p.DepartmentID=d.DepartmentID

use TescaStaging

IF OBJECT_ID('retail.product') is not null 
 Truncate table retail.product

Create Table retail.product
(
 productID int,
 ProductNumber nvarchar(50),
 Product nvarchar(50),
 Department nvarchar(50),
 unitPrice float,
 LoadDate datetime default getdate(),
 constraint retail_product_pk primary key(productid)
)

----- Loading product edw
use TescaStaging
Select  productID,ProductNumber,Product,Department,unitPrice  from  retail.product

use TescaEDW

select count(*) as PreCount from EDW.dimproduct

select count(*) as PostCount from EDW.dimproduct


select * from edw.dimproduct where EffectiveEndDate is null 

Create Table edw.dimproduct
(
 productsk int identity(1,1),
 productID int,
 ProductNumber nvarchar(50),
 Product nvarchar(50),
 Department nvarchar(50),
 unitPrice float,
 EffectiveStartDate datetime ,
 EffectiveEndDate datetime ,
 constraint edw_dimproduct_sk primary key(productsk)
)

---- loading promotion----

use TescaOLTP

select p.PromotionID, t.Promotion,p.StartDate as PromotionStartDate,p.EndDate as PromotionEndDate,p.DiscountPercent, 
getdate() as loadDate  from Promotion p 
inner join PromotionType t on p.PromotionTypeID=t.PromotionTypeID

select Count(*) as stgSourceCount  from Promotion p 
inner join PromotionType t on p.PromotionTypeID=t.PromotionTypeID

use TescaStaging

---drop table  retail.promotion
IF  OBJECT_ID('retail.promotion') is not null
   Truncate table  retail.promotion

Create table retail.promotion
(
 PromotionID int,
 Promotion nvarchar(50),
 PromotionStartDate date,
 PromotionEndDate date,
 DiscountPercent float,
 Loaddate datetime default getdate(),
 constraint retail_promotion_pk primary key(PromotionID)
)

----Loading into EDW
use TescaStaging
select  PromotionID,Promotion,PromotionStartDate,PromotionEndDate,DiscountPercent  from retail.promotion
---Where Cast(LoadDate as date)=cast(Getdate() as Date)

use TescaEDW

select count(*) as PreCount from edw.dimpromotion

select count(*) as PostCount from edw.dimpromotion

select * from edw.dimpromotion

Create table edw.dimpromotion
(
 PromotionSk int identity(1,1),
 PromotionID int,
 Promotion nvarchar(50),
 PromotionStartDate date,
 PromotionEndDate date,
 DiscountPercent float,
 EffectiveStartDate datetime,
 constraint edw_dimpromotion_sk primary key(Promotionsk)
)


----Loading Customer
--- Loading into Staging 
---E-> Extract Data  T->Tranform Data   L-> Load data
--- Combine Lastname and first name, then Lastname comes first in Upper Letters and seperate with comma into Staging
use TescaOLTP

select c.CustomerID, CONCAT_WS(', ',Upper(c.Lastname), c.FirstName) CustomerName,c.CustomerAddress, ct.CityName, s.State, getdate() as LoadDate  from Customer c 
inner join City ct on ct.CityID=c.CityID
inner join State s on s.StateID=ct.StateID

select count(*) as stgSourceCount  from Customer c 
inner join City ct on ct.CityID=c.CityID
inner join State s on s.StateID=ct.StateID


use TescaStaging

IF OBJECT_ID('retail.customer') is not null
  Truncate Table retail.Customer

Create table retail.Customer
(
 CustomerID int, 
 CustomerName nvarchar(250),
 CustomerAddress nvarchar(50),
 CityName nvarchar(50),
 State  nvarchar(50),
 LoadDate datetime default getdate(),
 constraint retail_customer_pk primary key (customerID)
)

--- Loading into the EDW
use TescaStaging

select  CustomerID, CustomerName, CustomerAddress, CityName,State  from retail.Customer

use TescaEDW

select count(*) as PreCount from EDW.dimCustomer

select count(*) as PostCount from EDW.dimCustomer

select * from EDW.dimCustomer

Create table EDW.dimCustomer
(
 CustomerSk int identity(1,1), 
 CustomerID int, 
 CustomerName nvarchar(250),
 CustomerAddress nvarchar(50),
 CityName nvarchar(50),
 State  nvarchar(50),
 EffectiveStartDate datetime,
 constraint edw_dimcustomer_sk primary key (customerSk)
)

---Loading POS 

-- Loading into Staging
use TescaOLTP

select p.ChannelID,p.ChannelNo ,p.DeviceModel,p.InstallationDate,p.SerialNo, getdate() as LoadDate from POSChannel p

select count(*) as stgSourceCount from POSChannel p

use TescaStaging

IF OBJECT_ID('retail.PosChannel') is not null
  Truncate Table retail.PosChannel


Create table retail.PosChannel 
(
 ChannelID int,
 ChannelNo nvarchar(50),
 DeviceModel nvarchar(50),
 InstallationDate date,
 SerialNo nvarchar(50),
 LoadDate datetime default getdate(),
 constraint retail_PosChannel_pk primary key (ChannelID)
 )

------ Loading EDW
use TescaStaging
select  ChannelID,ChannelNo,DeviceModel,InstallationDate,SerialNo  from retail.PosChannel 


use TescaEDW

select Count(*) as PreCount from edw.dimPosChannel 

select Count(*) as PostCount from edw.dimPosChannel 


Create table edw.dimPosChannel 
(
 ChannelSK int identity(1,1),
 ChannelID int,
 ChannelNo nvarchar(50),
 DeviceModel nvarchar(50),
 InstallationDate date,
 SerialNo nvarchar(50),
 EffectiveStartDate datetime,
 EffectiveEndDate datetime, 
 constraint edw_dimPosChannel_sk primary key (ChannelSK)
 )

 ---- Loading Vendor

 use TescaOLTP
 --- Combine Lastname and first name, then Lastname comes first in Upper Letters and seperate with comma into Staging
 select v.VendorID,v.VendorNo, Concat( Upper(v.LastName),', ',v.FirstName) as VendorName,v.RegistrationNo,
 v.VendorAddress, c.CityName,s.State,getdate() as LoadDate  from Vendor v 
 inner join city c on c.CityID=v.CityID
 inner join State s  on s.StateID=c.StateID


 select count(*) as stgSourceCount from Vendor v 
 inner join city c on c.CityID=v.CityID
 inner join State s  on s.StateID=c.StateID

 use TescaStaging

 
IF OBJECT_ID('retail.Vendor') is not null
  Truncate Table retail.Vendor

 create table retail.Vendor
 (
  VendorID int,
  VendorNo nvarchar(50),
  VendorName  nvarchar(250),
  RegistrationNo nvarchar(50),
  VendorAddress nvarchar(50),
  CityName  nvarchar(50),
  State nvarchar(50),
  LoadDate datetime default getdate(),
  constraint  retail_vendor_pk primary key(VendorID) 
 )

 ---- Loading into EDW
 use TescaStaging
 select  vendorID, VendorNo,VendorName,RegistrationNo,VendorAddress,CityName,State   from  retail.Vendor

 use TescaEDW

 select Count(*) as PreCount  from edw.dimVendor

 select Count(*) as PostCount  from edw.dimVendor

 create table edw.dimVendor
 (
  VendorSK int identity(1,1),
  VendorID int,
  VendorNo nvarchar(50),
  VendorName  nvarchar(250),
  RegistrationNo nvarchar(50),
  VendorAddress nvarchar(50),
  CityName  nvarchar(50),
  State nvarchar(50),
  EffectiveStartDate datetime,
  EffectiveEndDate datetime, 
  constraint  edw_vendor_sk primary key(VendorSk) 
 )

 ----- Loading Employee
 use TescaOLTP 
 --- Combine Lastname and first name, then Lastname comes first in Upper Letters and seperate with comma into Staging
 ----change Dob to DateofBirth

 select e.EmployeeID,e.EmployeeNo,concat_ws(', ',Upper(e.LastName),e.FirstName) as EmployeeName ,e.DoB as DateofBirth,
 m.MaritalStatus,getdate() as LoadDate from Employee e
 inner join  MaritalStatus m on m.MaritalStatusID=e.MaritalStatus

 select count(*) as stgSourceCount from Employee e
 inner join  MaritalStatus m on m.MaritalStatusID=e.MaritalStatus

 use TescaStaging
 
IF OBJECT_ID('retail.employee') is not null
  Truncate Table retail.employee

 Create table retail.employee
 (
   EmployeeID int, 
   EmployeeNo nvarchar(50),
   EmployeeName nvarchar(250),
   DateofBirth Date,
   MaritalStatus nvarchar(50),
   LoadDate datetime default getdate(),
   constraint retail_employee_pk primary key(employeeID)  
 )
 
----- Loading into EDW
Use TescaStaging

select  EmployeeID,EmployeeNo,EmployeeName,DateofBirth,MaritalStatus from retail.employee

use TescaEDW

select count(*) as PreCount from edw.dimemployee

select count(*) as PostCount from edw.dimemployee

select * from edw.dimemployee


Create table edw.dimemployee
 (
   EmployeeSk int identity(1,1), 
   EmployeeID int, 
   EmployeeNo nvarchar(50),
   EmployeeName nvarchar(250),
   DateofBirth Date,
   MaritalStatus nvarchar(50),
   EffectiveStartDate datetime,
   EffectiveEndDate datetime, 
  constraint  edw_dimemployee_sk primary key(EmployeeSk)    
 )
 


 -----Misconduct --- 
-- This will be loaded from csv file into staging 
use TescaStaging

create table hr.Misconduct
(
    Id int  identity(1,1),
	misconductid  int, 
	misconductdesc nvarchar(250),
	LoadDate Datetime default getdate(),
	constraint hr_misconduct_sk primary key(Id)
)

IF OBJECT_ID('hr.Misconduct') is not null
  Truncate Table hr.Misconduct


--- Loading into EDW 

use TescaStaging

select misconductid,misconductdesc  from hr.Misconduct
where id in ( select  max(id)  from hr.Misconduct group by misconductid)


use TescaEDW

select count(*) as PreCount from  Edw.dimMisconduct

select count(*) as PostCount from  Edw.dimMisconduct

create table Edw.dimMisconduct
(
    misconductsk int  identity(1,1),
	misconductid  int, 
	misconductdesc nvarchar(250),
	EffectiveStartDate Datetime, 
	constraint edw_dimmisconduct_sk primary key(misconductsk)
)

/*
---1.
select  distinct misconductid, misconductdesc from hr.misconduct

---2. 
 select  misconductid, misconductdesc from hr.misconduct
 group by misconductid, misconductdesc

 ----3  if one of the misconduct attribute change?
 --- introduce surrogate key id
 
select  min(id),misconductid  from mistest
group by misconductid


select misconductid,miscoductdesc  from mistest
where id in ( select  min(id)  from mistest group by misconductid)
*/


---- Loading Decision

IF OBJECT_ID('hr.Decision') is not null
  Truncate Table hr.Decision


use TescaStaging

create table hr.Decision
(    
	decision_id int, 
	decision nvarchar(250),
	LoadDate Datetime default getdate(),
	constraint hr_decision_pk primary key(decision_id)
)

--- Loading to EdW
use TescaStaging

select decision_id, decision  from hr.decision


use TescaEDW

select  count(*) as PreCount from  Edw.dimDecision

select  count(*) as PostCount from  Edw.dimDecision

create table Edw.dimDecision
( 
    decisionSk int  identity(1,1),
 	decision_id int, 
	decision nvarchar(250),
	EffectiveStartDate Datetime,
	constraint edw_dimdecision_sk primary key(decisionsk)
)


------  Loading Absent ----


IF OBJECT_ID('hr.Absent') is not null
  Truncate Table hr.Absent


use TescaStaging

create table hr.Absent
(    
	categoryid int, 
	category nvarchar(250),
	LoadDate Datetime default getdate(),
	constraint hr_absent_pk primary key(categoryid)
)

--- Loading to EdW
use TescaStaging

select categoryid,category from hr.absent


use TescaEDW

select count(*) as PreCount from  Edw.dimAbsent

select count(*) as PostCount from  Edw.dimAbsent

create table Edw.dimAsbsent
( 
    categorySk int  identity(1,1),
 	categoryid int, 
	category nvarchar(250),
	EffectiveStartDate Datetime,
	constraint edw_dimabsent_sk primary key( categorysk)
)

use TescaOLTP
select  * from SalesTransaction

 --   declare fname nvarchar(20)='sa owolabi'    10  unicode, the language specifica and adjusted the size based on the characters to be stored
 --   declare fname varchar(20)='sa owolabi'   non unicode, the language specifica and adjusted the size based on the characters to be stored
	--declare fname char(20)='sa owolabi      '  fixed and reserve the same of the size declared irrespective of the characters to be stored


use TescaEDW

create table Edw.dimTime 
(
 timesk int identity(1,1),
 dayhour  int,
 dayperiod nvarchar(50),
 dailydayhour nvarchar(50),
 Weekenddayhour nvarchar(50),
 effectivestartdate datetime,
 constraint edw_dimtime_sk primary key (timesk)
)

select * from edw.dimTime

--- Time   20:00:00.000    

----  dayhour  0 - 23  
---- dayperiod    0 - Mid night, 1 to 4  early hour  5 to 11  morning  12 noon , 13  to 17 afternoon   18 to  20 - evening  21 to 23 Night
---  dailydayHour  0 - 6  closed , 7 to 18 open , 19 - 23 closed
---  WeekenddayHour  0 -2   closed , 3 to 21 open, 22 - 23 closed

Create procedure EdW.spTimeGenerator 
AS

BEGIN
SET NOCOUNT ON;

 IF OBJECT_ID('edw.dimTime') is not null 
	 Truncate table edw.dimTime

declare @starthour int = 0 
 while @starthour<=23 
	begin 
		insert into edw.dimTime(dayhour,dayperiod,dailydayhour,Weekenddayhour,effectivestartdate)  
		select @starthour as dayhour, 
			case 
				when @starthour=0 then 'Mid Night'
				when @starthour>=1 and @starthour<=4 then 'Early Hour'
				when @starthour>=5 and @starthour<=11 then 'Morning'
				when @starthour=12 then 'Noon'
				when @starthour>=13 and @starthour<=17 then 'Afternoon'
				when @starthour>=18 and @starthour<=20 then 'Evening'
				when @starthour>=21 and @starthour<=23 then 'Night'
           end dayperiod,
		   case
		    when @starthour>=0 and @starthour<=6 then 'Closed'
			when @starthour>=7 and @starthour<=18 then 'Opened'
			when @starthour>=19 and @starthour<=23 then 'Closed'
		end dailydayhour,
		case
		    when @starthour>=0 and @starthour<=2 then 'Closed'
			when @starthour>=3 and @starthour<=21 then 'Opened'
			when @starthour>=22 and @starthour<=23 then 'Closed'
			end  as WeekendDayhour,
			GETDATE() as EffectiveStartDate
					   
	select @starthour =@starthour+1
	end
END


select * from edw.dimTime

exec EdW.spTimeGenerator 

--- DimDate ---------  2017-04-07
--- How do i determine Start date ---> Earliest date in transaction table {Sales, Purchase, overtime }
----   2012- 2100

select  Datefromparts(YEAR(getdate()),12,31)
select  datepart(WEEKDAY, getdate())
select DATENAME(dw,getdate())


use TescaEDW
---drop table EDW.dimdate
Create table EDW.dimdate
(
 datekey int, 
 BusinessDate date,
 BusinessYear int,
 BusinessMonth int,
 BusinessDay int,
 EnglishMonth nvarchar(50),
 EnglishDayofweek nvarchar(50),
 BusinessQuarter nvarchar(2),
 FrenchMonth nvarchar(50),
 FrenchDayofWeek nvarchar(50),
 EffectiveStartDate datetime,
 constraint edw_dimdate_sk primary key (datekey)
)


exec  EDW.spGenerateCalender 100

select * from edw.dimdate

select min(BusinessDate), max(BusinessDate) from edw.dimdate

create procedure EDW.spGenerateCalender (@generateYear int)
AS
BEGIN
 ----@generateYear int =70
 SET NOCOUNT ON;
 IF Object_id('EDW.DimDate') is not null 
   Truncate table EDW.DimDate

declare @startDate date = 
			(
				select min(convert(date,TransDate)) from TescaOltp.dbo.SalesTransaction 
					union 
				select min(convert(date,TransDate)) from  TescaOltp.dbo.PurchaseTransaction 
			)
declare @enddate date

select  @startDate=DATEADD(year,-1,@startDate)
select @enddate=dateadd(year, @generateYear, Datefromparts(YEAR(getdate()),12,31))
declare @noOfDays int =datediff(day,@startDate,@enddate)
declare @currentday int=0
declare @currentDate date
WHILE  @currentday<=@noOfDays
BEGIN 
	Select @currentDate=dateadd(day,@currentDay,@startdate)

	insert into EDW.dimdate(datekey,BusinessDate,BusinessYear,BusinessMonth,BusinessDay,EnglishMonth,EnglishDayofweek,BusinessQuarter,
	FrenchMonth,FrenchDayofWeek,EffectiveStartDate)
	select   convert(int,convert(nvarchar(8), @currentDate,112)) as DateKey, @currentDate as BusinessDate, year(@currentDate) as BusinessYear,
	datepart(Month,@currentDate) as BusinessMonth, day(@currentDate) as BusinessDay , DATENAME(Month,@CurrentDate) as EnglishMonth, 
	DATENAME(DW,@CurrentDate) as EnglishDayofweek,  concat('Q',DATEPART(Q,@currentDate)) BusinessQuarter,
	
	case datepart(Month,@currentDate)
	When 1 then 'Janvier' 	When 2 then 'février'  	When 3 then 'mars' 	When 4 then 'avril' When 5 then 'Mai'
	When 6 then 'Juin' When 7 then	'juillet'  When 8  then 'août' When 9 then 'septembre'  
	When 10 then 'octobre' When 11 then 'novembre'   When 12 then 'décembre' end FrenchMonth,

	case datepart(Weekday,@currentDate)
	When 1 then 'dimanche' 	When 2 then 'lundi'  	When 3 then 'mardi'	When 4 then 'mercredi' When 5 then 'jeudi'
	When 6 then 'vendredi' When 7 then	'samedi' end FrenchDayofWeek,
	getdate() as EffectiveStartDate
	
	select @currentday=@currentday+1
END
END

---FACT TABLES---

----Sales Analysis

use TescaOLTP

select min(TransDate), Max(TransDate) from SalesTransaction

select *  from SalesTransaction where Convert(date,TransDate)='2023-09-15'
---- Shift by 2 years to data for processing
update SalesTransaction 
 set TransDate = DATEADD(year, 2, TransDate),
    OrderDate = DATEADD(year, 2, OrderDate),
	DeliveryDate = DATEADD(year, 2, DeliveryDate)


use TescaOLTP


----- from the start the sales transaction till N-1
--- loading from OLTP to staging

use TescaOLTP

IF (select count(*) from TescaEDW.EdW.fact_salesAnalysis) = 0 
	select TransactionID,TransactionNO, Convert(Date, TransDate) TransDate, Datepart(Hour, TransDate) TransHour,
	Convert(Date, OrderDate) OrderDate, Datepart(Hour, OrderDate) OrderHour, Convert(Date, DeliveryDate) DeliveryDate,
	ChannelID,CustomerID,EmployeeID, ProductID,StoreID, PromotionID,Quantity,LineAmount
	From SalesTransaction  Where Convert(date,TransDate) <= convert(date,dateadd(DAY,-1,getdate()))
ELSE
	
	select TransactionID,TransactionNO, Convert(Date, TransDate) TransDate, Datepart(Hour, TransDate) TransHour,
	Convert(Date, OrderDate) OrderDate, Datepart(Hour, OrderDate) OrderHour, Convert(Date, DeliveryDate) DeliveryDate,
	ChannelID,CustomerID,EmployeeID, ProductID,StoreID, PromotionID,Quantity,LineAmount
	From SalesTransaction  Where Convert(date,TransDate) = convert(date,dateadd(DAY,-1,getdate()))


use TescaOLTP

IF (select count(*) from TescaEDW.EdW.fact_salesAnalysis) = 0 
    select count(*) as stgSourceCount From SalesTransaction  Where Convert(date,TransDate) <= convert(date,dateadd(DAY,-1,getdate()))
ELSE
	select count(*) as stgSourceCount	From SalesTransaction  Where Convert(date,TransDate) = convert(date,dateadd(DAY,-1,getdate()))




use TescaStaging

IF OBJECT_ID('retail.salestransaction') is not null 
   truncate table retail.salestransaction

create table retail.salestransaction
(
  TransactionID int,
  TransactionNo nvarchar(50),
  Transdate date,
  TransHour int,
  OrderDate date, 
  OrderHour int,
  deliveryDate date,
  ChannelID int,
  CustomerID int, 
  EmployeeId int,
  ProductID int,
  StoreID int, 
  PromotionID int,
  Quantity float,
  LineAmount float,
  LoadDate datetime,
  constraint retail_salestransaction_pk primary key (TransactionID)
)



---- Loading fact table
use TescaStaging

select  TransactionID, TransactionNo, Transdate,TransHour, OrderDate,OrderHour,deliveryDate,ChannelID,CustomerID,EmployeeId,
  ProductID,StoreID,PromotionID,Quantity,LineAmount, getdate() as LoadDate   from retail.salestransaction
  
  use TescaEDW

  select * from edw.fact_salesAnalysis

  select count(*) as PreCount from edw.fact_salesAnalysis

  select count(*) as PostCount from edw.fact_salesAnalysis

  truncate table EdW.fact_salesAnalysis

  create table EdW.fact_salesAnalysis
  ( 
	salesanalysisSk int identity(1,1),
	TransactionNo nvarchar(50),
	TransdateSk int,
	Transhoursk  int, 
	OrderdateSk int,
	Orderhoursk  int, 
	DeliverydateSk int,
	channelSK int,
	CustomerSK int,
	SalespersonSk int,
	ProductSk int,
    StoreSk int,   
	PromotionSk int,
    Quantity float,
	LineAmount float,
	LoadDate datetime,  
  constraint edw_fact_salesanalysis_sk primary key(salesanalysisSk),
  constraint fact_salesanalysis_transdate_sk  foreign key(TransdateSk) references edw.dimdate(datekey),
  constraint fact_salesanalysis_transhour_sk  foreign key(Transhoursk) references edw.dimtime(timesk),
  constraint fact_salesanalysis_Orderdate_sk  foreign key(OrderdateSk) references edw.dimdate(datekey),
  constraint fact_salesanalysis_Orderhour_sk  foreign key(Orderhoursk) references edw.dimtime(timesk),
  constraint fact_salesanalysis_deliverydate_sk  foreign key(DeliverydateSk) references edw.dimdate(datekey),
  constraint fact_salesanalysis_channel_sk foreign key(channelSK) references  edw.dimPoschannel(ChannelSk),
  constraint fact_salesanalysis_customer_sk foreign key(CustomerSK) references  edw.dimCustomer(CustomerSk),
  constraint fact_salesanalysis_salesperson_sk foreign key(SalespersonSk) references  edw.dimemployee(employeeSk),
  constraint fact_salesanalysis_product_sk foreign key(ProductSk) references  edw.dimProduct(ProductSk),
  constraint fact_salesanalysis_Store_sk foreign key(StoreSk) references  edw.dimStore(StoreSk),
  constraint fact_salesanalysis_Promotion_sk foreign key(PromotionSk) references  edw.dimPromotion(PromotionSk)
  
  )


  ----- Loading Purchase analysis

  use TescaOLTP

  select *  from PurchaseTransaction where convert(date,transdate)='2023-09-27'
  select min(TransDate), max(TransDate) from PurchaseTransaction

  --- shifting data for  2 yrs
  update PurchaseTransaction 
  set 
  TransDate= DATEADD(year,2,Transdate),
  OrderDate= DATEADD(year,2,OrderDate),
  DeliveryDate= DATEADD(year,2,DeliveryDate),
  ShipDate= DATEADD(year,2,ShipDate)

  ---from the begining till N-1
  use TescaOLTP
  
IF (select count(*) from TescaEDW.edw.fact_PurchaseAnalysis)=0

	SELECT TransactionID,TransactionNO,convert(date,TransDate) TransDate,convert(date,OrderDate) OrderDate,convert(date,DeliveryDate) DeliveryDate,
		convert(date,Shipdate) ShipDate,VendorID, EmployeeID,ProductID,StoreID,Quantity,LineAmount,
		datediff(day,OrderDate,DeliveryDate) +1 as diffDays,getdate() as LoadDate
		from PurchaseTransaction  where convert(date,TransDate)<=  dateadd(day,-1,  convert(date,getdate()))
ELSE

	SELECT TransactionID,TransactionNO,convert(date,TransDate) TransDate,convert(date,OrderDate) OrderDate,convert(date,DeliveryDate) DeliveryDate,
	convert(date,Shipdate) ShipDate,VendorID, EmployeeID,ProductID,StoreID,Quantity,LineAmount, datediff(day,OrderDate,DeliveryDate) +1 as diffDays,
	getdate() as LoadDate
	from PurchaseTransaction  where convert(date,TransDate)=  dateadd(day,-1,  convert(date,getdate()))

IF (select count(*) from TescaEDW.edw.fact_PurchaseAnalysis)=0

	SELECT count(*) as stgSourceCount	from PurchaseTransaction  where convert(date,TransDate)<=  dateadd(day,-1,  convert(date,getdate()))
ELSE

	SELECT count(*) as stgSourceCount	from PurchaseTransaction  where convert(date,TransDate)=  dateadd(day,-1,  convert(date,getdate()))


 use TescaStaging

 select * from retail.PurchaseAnalysis
 
IF OBJECT_ID('retail.PurchaseAnalysis') is not null 
   truncate table retail.PurchaseAnalysis
  
 --- drop  table retail.PurchaseAnalysis   to add load Date column

 create table retail.PurchaseAnalysis
 (
   TransactionID int,
   TransactionNO nvarchar(50),
   TransDate date,
   OrderDate date,
   DeliveryDate date,
   ShipDate date,
   VendorID int,
   EmployeeID int,
   ProductID int,
   StoreID int,
   Quantity float,
   LineAmount float,
   diffDays int,
   LoadDate datetime default getdate(),
  constraint retail_PurchaseAnalysis_pk primary key (TransactionID) 
 )

 use TescaStaging
 select  TransactionID,TransactionNO,TransDate, OrderDate,DeliveryDate,ShipDate,VendorID,EmployeeID,ProductID,StoreID,Quantity,
 LineAmount,diffDays, getDate() as LoadDate from retail.PurchaseAnalysis

  
  use TescaEDW

  select count(*) as PreCount from EdW.fact_PurchaseAnalysis

  select count(*) as PostCount from EdW.fact_PurchaseAnalysis
  
  create table EdW.fact_PurchaseAnalysis
  ( 
	PurchaseanalysisSk int identity(1,1),
	TransactionNo nvarchar(50),
	TransdateSk int,	
	OrderdateSk int,	
	DeliverydateSk int,
	ShipDateSk int,
	Vendorsk int,	
	PurchaserSk int,
	ProductSk int,
    StoreSk int,   	
    Quantity float,
	LineAmount float,
	diffDays int,
	LoadDate datetime,  
  constraint edw_fact_purchaseanalysis_sk primary key(PurchaseanalysisSk),
  constraint fact_Purchaseanalysis_transdate_sk  foreign key(TransdateSk) references edw.dimdate(datekey),  
  constraint fact_Purchaseanalysis_Orderdate_sk  foreign key(OrderdateSk) references edw.dimdate(datekey),  
  constraint fact_Purchaseanalysis_deliverydate_sk  foreign key(DeliverydateSk) references edw.dimdate(datekey),
  constraint fact_Purchaseanalysis_ShipDate_sk  foreign key(ShipDateSk) references edw.dimdate(datekey),  
  constraint fact_Purchaseanalysis_Vendorsk foreign key(VendorSK) references  edw.dimVendor(VendorSk),
  constraint fact_Purchaseanalysis_Purchaser_sk foreign key(PurchaserSk) references  edw.dimemployee(employeeSk),
  constraint fact_Purchaseanalysis_product_sk foreign key(ProductSk) references  edw.dimProduct(ProductSk),
  constraint fact_Purchaseanalysis_Store_sk foreign key(StoreSk) references  edw.dimStore(StoreSk)  
  )

---- Overtime loading

--OvertimeID,EmployeeNo,FirstName,LastName,StartOvertime,EndOvertime

use TescaStaging

IF Object_ID('hr.overtime') is not null
 TRUNCATE Table hr.overtime

---- Duplicate data is seen and this need to go for deduplication processing
--- recreate hr.overtime and use surrogate key to handle primary key
--- Business stakeholder advised to use business rule: first record as right 

use TescaStaging

---drop table hr.Overtime

create table hr.Overtime
(
 OvertimeSk int identity(1,1),
 OvertimeID int,
 EmployeeNo nvarchar(50),
 FirstName nvarchar(50),
 LastName nvarchar(50),
 StartOvertime datetime,
 EndOvertime datetime,
 LoadDate datetime default getdate(),
 constraint hr_overtime_overtimesk_Pk primary key(overtimeSk)
)

---loading into EDW----
--- from the begining till N-1 or N-1 data
select count(*) from  hr.Overtime

use TescaStaging
select EmployeeNo, convert(date,startOvertime) StartOvertimeDate, DATEPART(hour,StartOvertime) startOvertimeHour,
convert(date,EndOvertime) EndOvertimeDate, DATEPART(hour,EndOvertime) EndOvertimeHour
from hr.Overtime  Where OvertimeSk in  ( select min(overtimesK) from hr.Overtime group by OvertimeID,EmployeeNo,convert(date,startOvertime))




---- Loading to EDW----
use TescaEDW

select count(*) as edwCount from  EDW.fact_OvertimeAnalysis

drop table EDW.fact_OvertimeAnalysis

select count(*) as PreCount from EDW.fact_OvertimeAnalysis

select count(*) as PostCount from EDW.fact_OvertimeAnalysis

Create table EDW.fact_OvertimeAnalysis
(
	OvertimeAnalysisSk int identity(1,1),
	EmployeeSk int,
	StartOvertimeDateSk int,
	StartOvertimeHourSk int,
	EndOvertimeDateSk int,
	EndOvertimeHourSk int,
	TotalHour int,   --- 
	LoadDate datetime,
	constraint Fact_OvertimeAnalysis_Sk  primary key(OvertimeAnalysisSk),
	constraint fact_overtimeanalysis_employeesk foreign key(EmployeeSk) references edw.dimemployee(employeesk),
	constraint fact_overtimeanalysis_startovertimedatesk foreign key(StartOvertimeDateSk) references edw.dimdate(datekey),
	constraint fact_overtimeanalysis_startovertimehoursk foreign key(StartOvertimeHourSk) references edw.dimtime(timesk),
	constraint fact_overtimeanalysis_Endovertimedatesk foreign key(EndOvertimeDateSk) references edw.dimdate(datekey),	
	constraint fact_overtimeanalysis_Endovertimehoursk foreign key(EndOvertimeHourSk) references edw.dimtime(timesk)
 )


 truncate table [hr].[absentanalysis]

 ----- Loading absent data -----

 ---- empid,store,absent_date,absent_hour,absent_category

 use TescaStaging

 if OBJECT_ID('hr.absentanalysis') is not null 
    TRUNCATE table hr.absentanalysis


 create table hr.absentanalysis
 (
   absentid int identity(1,1),
   empid int,
   store int,
   absent_date date,
   absent_category int, 
   absent_hour int,
   loaddate datetime,
   constraint hr_absentanalysis_absent_pk primary key(absentid)  
 )
 
 ----The first entry of the absence data for a day is the right record to be retained
 ---N-1 and begining to N-1 needed to be taken off by ETL pipeline processing 

 --- To dedup data
 select empid,store,absent_date,absent_category,absent_hour   from hr.absentanalysis 
 where absentid in ( select min(absentid)  from hr.absentanalysis  group by  empid,store,absent_date,absent_category)

 ---Loading EDW----
 use TescaEDW

 select  count(*) as edwCount from edw.fact_absentAnalysis

 select count(*) as PreCount from edw.fact_absentAnalysis

 select count(*) as PostCount from edw.fact_absentAnalysis


 create table edw.fact_absentAnalysis
 (
   absentAnalysisSk int identity(1,1),
   employeesk int, 
   storesk int,
   absent_datesk int,
   absent_categorysk int,   
   absent_hour int,
   loaddate datetime,
   constraint fact_absentAnalysis_Sk primary key(absentAnalysisSk),
   constraint fact_absentAnalysis_employeesk foreign key(employeesk) references edw.dimemployee(employeesk),
   constraint fact_absentAnalysis_storesk foreign key(storesk) references edw.dimstore(storesk),
   constraint fact_absentAnalysis_absent_datesk foreign key(absent_datesk) references edw.dimdate(datekey),
   constraint fact_absentAnalysis_absent_categorysk foreign key(absent_categorysk) references edw.dimAsbsent(categorySk)      
 )


 ------- Misconduct analysis 

 ---empid,storeid,misconduct_date,misconduct_id,decision_id

 use TescaStaging

 IF OBJECT_ID('hr.misconductanalysis') is not null 
   TRUNCATE table hr.misconductanalysis

-- begining to N-1  or N-1

 create table hr.misconductanalysis
 ( 
	misconductpk int identity(1,1),
	empid int,
	storeid int,
	misconduct_date date,
	misconduct_id int,
	decision_id int,
	loaddate datetime default getdate(),
	constraint hr_misconductanalysis_pk primary key(misconductpk)
 )
 
 
 select empid,storeid,misconduct_date,misconduct_id,decision_id, getdate() as LoadDate  from hr.misconductanalysis
  where misconductpk in (select  max(misconductpk) from hr.misconductanalysis group by empid,storeid,misconduct_date,misconduct_id)


  
  ---- Loading EdW----

  use TescaEDW

  select count(*) as edwCount from edw.fact_Misconductanalysis


   select count(*) as PreCount from edw.fact_Misconductanalysis

   select count(*) as PostCount from edw.fact_Misconductanalysis

  create table edw.fact_Misconductanalysis
  (
    MisconductanalysisSk int identity(1,1),
	employeeSk int,
	storesk int,
	misconductdatesk int,
	misconductsk int,
	decisionsk int,
	LoadDate datetime,  
  constraint fact_Misconductanalysis_sk primary key (MisconductanalysisSk),
  constraint fact_Misconductanalysis_employeesk  foreign key (employeeSk) references edw.dimemployee(employeesk),
  constraint fact_Misconductanalysis_storesk  foreign key (storesk) references edw.dimstore(storesk),
  constraint fact_Misconductanalysis_misconductdatesk  foreign key (misconductdatesk) references edw.dimdate(datekey),
  constraint fact_Misconductanalysis_misconductsk  foreign key (misconductsk) references edw.dimMisconduct(misconductsk),
  constraint fact_Misconductanalysis_decisionsk  foreign key (decisionsk) references edw.dimdecision(decisionsk)

	)


  use TescaEDW
  truncate table [edw].[fact_absentAnalysis]

  truncate table [edw].[fact_Misconductanalysis]

  truncate table [edw].[fact_OvertimeAnalysis]
  truncate table [edw].[fact_PurchaseAnalysis]
  truncate table [edw].[fact_salesAnalysis]

  select count(*) from [edw].[fact_salesAnalysis]


  ------ ssrs Tesca sales Analysis
  --1. Total Amount, Total Quantity , based on Product category and  year

  use TescaEDW

  create procedure edw.spSalesAnalysisByYear
  as
  BEGIN
  set nocount on;
	select  d.BusinessYear, sum(lineAmount) TotalAmount, sum(Quantity) as TotalQuantity from 
  edw.fact_salesAnalysis  s  inner join edw.dimdate d  on s.TransdateSk=d.datekey 
  group by d.BusinessYear
  END 
  ---order by d.BusinessYear

  --
  --exec  edw.spSalesAnalysisByYearDept 2016

  
  create procedure edw.spSalesAnalysisByYearDept(@BusinessYear int)
  AS
  BEGIN
  set nocount on;
   select d.BusinessYear, p.Department, sum(lineAmount) TotalAmount, sum(Quantity) as TotalQuantity from 
   edw.fact_salesAnalysis  s 
  inner join edw.dimdate d  on s.TransdateSk=d.datekey 
  inner join edw.dimproduct p on s.ProductSk=p.productsk
  Where d.BusinessYear=@BusinessYear
  group by d.BusinessYear,p.Department
 END
  
  ---order by d.BusinessYear

  create procedure edw.spSalesAnalysisYearDepprom(@BusinessYear int, @Department nvarchar(50))
  AS 
  BEGIN 
  set nocount on;
  ---- comment can be here
  select d.BusinessYear, p.Department, pm.Promotion, sum(lineAmount) TotalAmount, sum(Quantity) as TotalQuantity from 
  edw.fact_salesAnalysis  s 
  inner join edw.dimdate d  on s.TransdateSk=d.datekey 
  inner join edw.dimproduct p on s.ProductSk=p.productsk
  inner join edw.dimpromotion pm  on s.PromotionSk=pm.PromotionSk
  Where d.BusinessYear=@BusinessYear and p.Department=@Department
  group by d.BusinessYear,p.Department,pm.Promotion
END


select d.BusinessYear, p.Department, p.Product, pm.Promotion, sum(lineAmount) TotalAmount, sum(Quantity) as TotalQuantity from 
  edw.fact_salesAnalysis  s 
  inner join edw.dimdate d  on s.TransdateSk=d.datekey 
  inner join edw.dimproduct p on s.ProductSk=p.productsk
  inner join edw.dimpromotion pm  on s.PromotionSk=pm.PromotionSk
  Where d.BusinessYear=@BusinessYear and p.Department=@Department
  group by d.BusinessYear,p.Department, p.Product,pm.Promotion



  select BusinessYear  from edw.dimdate d
  inner join edw.fact_salesAnalysis s  on d.datekey=s.TransdateSk
  group by BusinessYear
  order by BusinessYear

  2. Total Amount, Total Quantity , based on Product 
















































 











